name: Publish to VS Code Marketplace

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      # Install & build
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Test vsce pack
        run: |
          echo "\n\n  # vsce ls\n"
          pnpm exec vsce ls --tree
          echo "\n\n  # vsce pack\n"
          pnpm exec vsce pack
          echo "\n\n  # du -h *.vsix\n"
          du -h *.vsix
      # ───────────────────────────────
      # Derive version and release type
      #
      # v0.0.* => pré-release (MAJOR=MINOR=0)
      # v*.1.* => pré-release (MINOR is odd)
      # v*.2.* => release     (MINOR is even)
      # ───────────────────────────────
      - name: Is pre-release?
        id: semver
        run: |
          # Get version from tag input or from github release event
          if [[ -n "$TAG_NAME" ]]; then
              RAW="${TAG_NAME#v}"          # drop leading 'v'
          else
              RAW="${GITHUB_REF#refs/tags/v}"  # From release event, drop refs/tags/v
          fi

          echo "version=$RAW" >> "$GITHUB_OUTPUT"

          # Read version as 'vMAJOR.MINOR.PATCH'
          IFS='.' read -r MAJOR MINOR PATCH <<< "$RAW"
          if (( MINOR % 2 )) || (( MAJOR == 0 && MINOR == 0 )); then
              echo "prerelease=yes" >> "$GITHUB_OUTPUT"   # odd or 0.0.x => pre-release
          else
              echo "prerelease=no" >> "$GITHUB_OUTPUT"    # even => release
          fi
      # Publish
      - name: Publish to Marketplace
        run: |
          if [[ "${{ steps.semver.outputs.prerelease }}" == "yes" ]]; then
            pnpm run prepublish
          else
            pnpm run publish
          fi

        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
