name: Publish to VS Code Marketplace

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test


  publish:
    runs-on: ubuntu-latest
    needs: test
    env:
      TAG_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      # ───────────────────────────────
      # Derive version and release type
      #
      # v0.0.* => pré-release (MAJOR=MINOR=0)
      # v*.1.* => pré-release (MINOR is odd)
      # v*.2.* => release     (MINOR is even)
      # ───────────────────────────────
      - name: Parse SemVer from tag
        id: semver
        run: |
          RAW="${TAG_NAME#v}"          # drop leading 'v'
          echo "version=$RAW" >> "$GITHUB_OUTPUT"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$RAW"
          if (( MINOR % 2 )) || (( MAJOR == 0 && MINOR == 0 )); then
            echo "prerelease=yes"  >> "$GITHUB_OUTPUT"   # odd or 0.0.x => pre-release
          else
            echo "prerelease=no"   >> "$GITHUB_OUTPUT"   # even => release
          fi

      # Install & build
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Publish with or without --pre-release
      - name: Publish to Marketplace
        run: |
          if [[ "${{ steps.semver.outputs.prerelease }}" == "yes" ]]; then
            pnpm run prepublish
          else
            pnpm run publish
          fi

        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
